spring:
  security:
    user:
      name: admin
      password: admin123
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:aerovia;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # o validate si usas Flyway con scripts H2-friendly
    defer-datasource-initialization: true
  flyway:
    enabled: false            # desactívalo si no tienes scripts compatibles con H2
